import { createClient } from "@/libs/supabase/server";
import { getCurrentTeamId } from "@/libs/team";
import { NextRequest, NextResponse } from "next/server";

export interface ApiKeyResponse {
  id: string;
  name: string;
  api_key: string;
  created_at: string;
  last_used_at: string | null;
  revoked_at: string | null;
  created_by: string | null;
}

/**
 * GET /api/api-keys
 * List all API keys for the current team (including revoked ones)
 */
export async function GET() {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const teamId = await getCurrentTeamId(supabase, user.id);
    if (!teamId) {
      return NextResponse.json({ error: "No team found" }, { status: 404 });
    }

    const { data: keys, error } = await supabase
      .from("team_api_keys")
      .select("id, name, api_key, created_at, last_used_at, revoked_at, created_by")
      .eq("team_id", teamId)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching API keys:", error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ keys: keys || [] });
  } catch (error) {
    console.error("Error in GET /api/api-keys:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/api-keys
 * Create a new API key for the current team
 * Requires admin or owner role
 */
export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const teamId = await getCurrentTeamId(supabase, user.id);
    if (!teamId) {
      return NextResponse.json({ error: "No team found" }, { status: 404 });
    }

    // Check user role (RLS will also enforce this, but better UX to check first)
    const { data: membership } = await supabase
      .from("team_members")
      .select("role")
      .eq("team_id", teamId)
      .eq("user_id", user.id)
      .single();

    if (!membership || !["owner", "admin"].includes(membership.role)) {
      return NextResponse.json(
        { error: "Admin or owner access required" },
        { status: 403 }
      );
    }

    const { name } = await req.json();

    if (!name || typeof name !== "string" || name.trim().length === 0) {
      return NextResponse.json(
        { error: "Name is required" },
        { status: 400 }
      );
    }

    if (name.length > 50) {
      return NextResponse.json(
        { error: "Name must be 50 characters or less" },
        { status: 400 }
      );
    }

    // Insert new key (api_key is auto-generated by DEFAULT)
    const { data: newKey, error } = await supabase
      .from("team_api_keys")
      .insert({
        team_id: teamId,
        name: name.trim(),
        created_by: user.id,
      })
      .select("id, name, api_key, created_at, last_used_at, revoked_at, created_by")
      .single();

    if (error) {
      console.error("Error creating API key:", error);
      // Check for unique constraint violation
      if (error.code === "23P01") {
        return NextResponse.json(
          { error: "An active key with this name already exists" },
          { status: 409 }
        );
      }
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ key: newKey }, { status: 201 });
  } catch (error) {
    console.error("Error in POST /api/api-keys:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
