name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm to latest (requires >= 11.5.1 for OIDC)
        run: npm install -g npm@latest && npm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Update version from release tag
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          npm version "$VERSION" --no-git-tag-version --allow-same-version

      - name: Publish to npm
        run: npm publish --access public
